---
language: python
cache: pip
python: "2.7"

# Use the new container infrastructure
sudo: false

# exclude release tags like 1.0.0
branches:
  except:
  - /^\d+(\.\d+\.\d+)?(\..*|\-.*)?$/

# Install pip
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible and dependencies
  - pip install ansible ansible-lint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=./tests/requirements/:../' > ansible.cfg

script:
  # Install requirements
  - ansible-galaxy install -r tests/requirements.yml -p ./tests/requirements

  # Run ansible-lint
  - ansible-lint .

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
